version: '3.9'

services:
  mongodb:
    image: mongo:8.0
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root1235
    volumes:    #todo lo que esta en data/db guardalo en mongo_data
      - ./mongo_data:/data/db    